name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check uppgift.md size
      id: check-uppgift-md-size
      uses: education/autograding-python-grader@v1
      with:
        timeout: 11
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CHECK-UPPGIFT-MD-SIZE_RESULTS: "${{steps.check-uppgift-md-size.outputs.result}}"
      with:
        runners: check-uppgift-md-size
